CREATE TABLE [VEHICLE] (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    PLATE VARCHAR(7),
    INCIALKM FLOAT,
    ACTUALKM FLOAT
);

CREATE TABLE [SUPPLY] (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    VEHICLEID INT NOT NULL,
    KM FLOAT,
    QUANTITY FLOAT,
    DATE_SUPPLY FLOAT,
    VALUE_SUPPLY FLOAT,
);

-- Chage this to insert your first Vehicle
-- INSERT INTO [VEHICLE] (PLATE,INCIALKM, ACTUALKM)
-- VALUES ('RAD3F42',33338,33338);